services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"  # Web UI
      - "7077:7077"  # Spark Cluster
    volumes:
      - ./spark-default.conf:/opt/spark/conf/spark-default.conf
      - ./jars:/opt/spark/jars
    user: root
    command: bash -c "apt-get update && apt-get install -y curl && spark-class org.apache.spark.deploy.master.Master"

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web UI
    volumes:
      - ./set_minio.sh:/usr/bin/set_minio.sh
      - ./batches:/batches
    entrypoint: ["/bin/sh", "-c", "minio server /data --console-address ':9001' & sleep 5 && chmod +x /usr/bin/set_minio.sh && /usr/bin/set_minio.sh && wait"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
